### ISSUE TITLE
Handicapped Space Issues on Map/Satellite View and Zoom Levels

### ISSUE THREAD

**Issue by umayavuz** [umts/ParkingMap#30]
Handicapped icons disappear in the Map view. It looks different in the satellite view. (Example: handicapped spaces in the Old Chapel). The spaces in the Old Chapel also disappear in the different zoom levels too.

There are currently no handicapped spaces near Old Chapel. Can we remove them? There is an event in the old chapel so if we can remove these spaces first asap, that will be great.

**Comment by Anbranin** [comment]
Closed with ab1c1b5f905ae8b27630944d8737054c30aa78aa. Tilting the map screws up the icon placement. Tilt automatically occurs when in satellite view and at a certain view level UNLESS YOU DISABLE IT HAHA
